var GitHubObjects = {
  users : {
    show : { 
      "login": "runemadsen",
      "id": 1,
      "avatar_url": "https://github.com/images/error/octocat_happy.gif",
      "gravatar_id": "somehexcode",
      "url": "https://api.github.com/users/runemadsen",
      "name": "rune madsen",
      "company": "O'Reilly MEdia",
      "blog": "https://github.com/blog",
      "location": "San Francisco",
      "email": "runemadsen@github.com",
      "hireable": false,
      "bio": "There once was...",
      "public_repos": 2,
      "public_gists": 1,
      "followers": 20,
      "following": 0,
      "html_url": "https://github.com/runemadsen",
      "created_at": "2008-01-14T04:33:35Z",
      "type": "User"
    }
  },
  orgs : {
    index : [
      {
        "login": "oreillymedia",
        "id": 1,
        "url": "https://api.github.com/orgs/oreillymedia",
        "avatar_url": "https://github.com/images/error/octocat_happy.gif"
      }
    ],
    show : {
      "login": "oreillymedia",
      "id": 1,
      "url": "https://api.github.com/orgs/oreillymedia",
      "avatar_url": "https://github.com/images/error/octocat_happy.gif",
      "name": "oreillymedia",
      "company": "O'Reilly Media",
      "blog": "https://oreilly.com/blog",
      "location": "Sebastopol",
      "email": "oreillymedia@github.com",
      "public_repos": 2,
      "public_gists": 1,
      "followers": 20,
      "following": 0,
      "html_url": "https://github.com/oreillymedia",
      "created_at": "2008-01-14T04:33:35Z",
      "type": "Organization"
    }
  },
  repos : {
    index : [
      { 
        "id": 1296269,
        "owner": { "login": "runemadsen",
        "id": 1,
        "avatar_url": "https://github.com/images/error/octocat_happy.gif",
        "gravatar_id": "somehexcode",
        "url": "https://api.github.com/users/runemadsen" },
        "name": "Hello-World",
        "full_name": "runemadsen/Hello-World",
        "description": "This your first repo!",
        "private": false,
        "fork": false,
        "url": "https://api.github.com/repos/runemadsen/Hello-World",
        "html_url": "https://github.com/runemadsen/Hello-World",
        "clone_url": "https://github.com/runemadsen/Hello-World.git",
        "git_url": "git://github.com/runemadsen/Hello-World.git",
        "ssh_url": "git@github.com:octocat/Hello-World.git",
        "svn_url": "https://svn.github.com/runemadsen/Hello-World",
        "mirror_url": "git://git.example.com/runemadsen/Hello-World",
        "homepage": "https://github.com",
        "language": null,
        "forks": 9,
        "forks_count": 9,
        "watchers": 80,
        "watchers_count": 80,
        "size": 108,
        "master_branch": "master",
        "open_issues": 0,
        "pushed_at": "2011-01-26T19:06:43Z",
        "created_at": "2011-01-26T19:01:12Z",
        "updated_at": "2011-01-26T19:14:43Z"
      },
      { 
        "id": 1296270,
        "owner": { "login": "runemadsen",
        "id": 1,
        "avatar_url": "https://github.com/images/error/octocat_happy.gif",
        "gravatar_id": "somehexcode",
        "url": "https://api.github.com/users/runemadsen" },
        "name": "Hello-Again",
        "full_name": "runemadsen/Hello-Again",
        "description": "This your first repo!",
        "private": false,
        "fork": false,
        "url": "https://api.github.com/repos/runemadsen/Hello-Again",
        "html_url": "https://github.com/runemadsen/Hello-Again",
        "clone_url": "https://github.com/runemadsen/Hello-Again.git",
        "git_url": "git://github.com/runemadsen/Hello-Again.git",
        "ssh_url": "git@github.com:octocat/Hello-Again.git",
        "svn_url": "https://svn.github.com/runemadsen/Hello-Again",
        "mirror_url": "git://git.example.com/runemadsen/Hello-Again",
        "homepage": "https://github.com",
        "language": null,
        "forks": 9,
        "forks_count": 9,
        "watchers": 80,
        "watchers_count": 80,
        "size": 108,
        "master_branch": "master",
        "open_issues": 0,
        "pushed_at": "2011-01-26T19:06:43Z",
        "created_at": "2011-01-26T19:01:12Z",
        "updated_at": "2011-01-26T19:14:43Z"
      }
    ],
    show : {
      "id": 1296269,
      "owner": {
        "login": "runemadsen",
        "id": 1,
        "avatar_url": "https://github.com/images/error/octocat_happy.gif",
        "gravatar_id": "somehexcode",
        "url": "https://api.github.com/users/runemadsen"
      },
      "name": "Hello-World",
      "full_name": "runemadsen/Hello-World",
      "description": "This your first repo!",
      "private": false,
      "fork": false,
      "url": "https://api.github.com/repos/runemadsen/Hello-World",
      "html_url": "https://github.com/runemadsen/Hello-World",
      "clone_url": "https://github.com/runemadsen/Hello-World.git",
      "git_url": "git://github.com/runemadsen/Hello-World.git",
      "ssh_url": "git@github.com:runemadsen/Hello-World.git",
      "svn_url": "https://svn.github.com/runemadsen/Hello-World",
      "mirror_url": "git://git.example.com/runemadsen/Hello-World",
      "homepage": "https://github.com",
      "language": null,
      "forks": 9,
      "forks_count": 9,
      "watchers": 80,
      "watchers_count": 80,
      "size": 108,
      "master_branch": "master",
      "open_issues": 0,
      "pushed_at": "2011-01-26T19:06:43Z",
      "created_at": "2011-01-26T19:01:12Z",
      "updated_at": "2011-01-26T19:14:43Z",
      "organization": {
        "login": "runemadsen",
        "id": 1,
        "avatar_url": "https://github.com/images/error/octocat_happy.gif",
        "gravatar_id": "somehexcode",
        "url": "https://api.github.com/users/runemadsen",
        "type": "Organization"
      },
      "parent": {
        "id": 1296269,
        "owner": {
          "login": "runemadsen",
          "id": 1,
          "avatar_url": "https://github.com/images/error/octocat_happy.gif",
          "gravatar_id": "somehexcode",
          "url": "https://api.github.com/users/runemadsen"
        },
        "name": "Hello-World",
        "full_name": "runemadsen/Hello-World",
        "description": "This your first repo!",
        "private": false,
        "fork": false,
        "url": "https://api.github.com/repos/runemadsen/Hello-World",
        "html_url": "https://github.com/runemadsen/Hello-World",
        "clone_url": "https://github.com/runemadsen/Hello-World.git",
        "git_url": "git://github.com/runemadsen/Hello-World.git",
        "ssh_url": "git@github.com:runemadsen/Hello-World.git",
        "svn_url": "https://svn.github.com/runemadsen/Hello-World",
        "mirror_url": "git://git.example.com/runemadsen/Hello-World",
        "homepage": "https://github.com",
        "language": null,
        "forks": 9,
        "forks_count": 9,
        "watchers": 80,
        "watchers_count": 80,
        "size": 108,
        "master_branch": "master",
        "open_issues": 0,
        "pushed_at": "2011-01-26T19:06:43Z",
        "created_at": "2011-01-26T19:01:12Z",
        "updated_at": "2011-01-26T19:14:43Z"
      },
      "source": {
        "id": 1296269,
        "owner": {
          "login": "runemadsen",
          "id": 1,
          "avatar_url": "https://github.com/images/error/octocat_happy.gif",
          "gravatar_id": "somehexcode",
          "url": "https://api.github.com/users/runemadsen"
        },
        "name": "Hello-World",
        "full_name": "runemadsen/Hello-World",
        "description": "This your first repo!",
        "private": false,
        "fork": false,
        "url": "https://api.github.com/repos/runemadsen/Hello-World",
        "html_url": "https://github.com/runemadsen/Hello-World",
        "clone_url": "https://github.com/runemadsen/Hello-World.git",
        "git_url": "git://github.com/runemadsen/Hello-World.git",
        "ssh_url": "git@github.com:runemadsen/Hello-World.git",
        "svn_url": "https://svn.github.com/runemadsen/Hello-World",
        "mirror_url": "git://git.example.com/runemadsen/Hello-World",
        "homepage": "https://github.com",
        "language": null,
        "forks": 9,
        "forks_count": 9,
        "watchers": 80,
        "watchers_count": 80,
        "size": 108,
        "master_branch": "master",
        "open_issues": 0,
        "pushed_at": "2011-01-26T19:06:43Z",
        "created_at": "2011-01-26T19:01:12Z",
        "updated_at": "2011-01-26T19:14:43Z"
      },
      "has_issues": true,
      "has_wiki": true,
      "has_downloads": true
    } 
  }
};